import * as React from "react";
import {
  // bases
  Phone, PhoneCall, Users, ClipboardList, ListOrdered, Drama, Lightbulb,
  UserX, UserCheck, RefreshCw, DoorOpen, Target, ShieldCheck, CheckCircle,
  Heart, BadgeCheck, Megaphone, Armchair, Share2, Flame, BarChart2,
  HelpCircle, Ban, Crown, Shuffle, Eye, GitBranch, Zap, MessageCircle,
  ArrowRightLeft, Rocket, Reply, Search, FileText, Building, PlusCircle,
  Home, Handshake,
  // accents
  Snowflake, Clock, Sparkles, ArrowRight, Star, Check, Tag, Coffee,
  TriangleAlert, CreditCard, MapPin,
} from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * Single source of truth for the flat two-color icon system.
 * Brand colours: grey #52626F (subject) + red #D6071A (accent).
 * Tune the whole set's line weight from one place.
 */
export const ICON_STROKE = 2.3;        // base subject line weight
export const ICON_ACCENT_STROKE = 2.7; // accent line weight (drawn smaller, so a touch bolder)
const GREY = "#52626F";
const RED = "#D6071A";

type LucideIcon = React.ComponentType<{
  className?: string;
  strokeWidth?: number;
  style?: React.CSSProperties;
}>;

const REGISTRY: Record<string, LucideIcon> = {
  Phone: PhoneCall, PhoneCall, Users, ClipboardList, ListOrdered, Drama,
  Lightbulb, UserX, UserCheck, RefreshCw, DoorOpen, Target, ShieldCheck,
  CheckCircle, Heart, BadgeCheck, Megaphone, Armchair, Share2, Flame,
  BarChart2, HelpCircle, Ban, Crown, Shuffle, Eye, GitBranch, Zap,
  MessageCircle, ArrowRightLeft, Rocket, Reply, Search, FileText, Building,
  PlusCircle, Home, Handshake,
  Snowflake, Clock, Sparkles, ArrowRight, Star, Check, Tag, Coffee,
  TriangleAlert, CreditCard, MapPin,
};

/**
 * Default red accent for each base icon, so every concept gets a consistent
 * red highlight (echoing the homepage call/meeting icons). Override per-node
 * via NavNode.iconAccent.
 */
const DEFAULT_ACCENT: Record<string, string> = {
  ClipboardList: "Check",
  UserX: "Snowflake",
  UserCheck: "Flame",
  RefreshCw: "Clock",
  Lightbulb: "Sparkles",
  ListOrdered: "ArrowRight",
  DoorOpen: "MessageCircle",
  Target: "Megaphone",
  ShieldCheck: "MessageCircle",
  CheckCircle: "Handshake",
  Drama: "Sparkles",
  Heart: "Star",
  BadgeCheck: "Check",
  Megaphone: "Tag",
  Armchair: "Coffee",
  Share2: "Users",
  Users: "MessageCircle",
  Flame: "TriangleAlert",
  BarChart2: "Search",
  HelpCircle: "Clock",
  Ban: "TriangleAlert",
  Crown: "Star",
  Shuffle: "TriangleAlert",
  Eye: "Search",
  GitBranch: "HelpCircle",
  Zap: "ArrowRight",
  MessageCircle: "Users",
  ArrowRightLeft: "RefreshCw",
  Rocket: "ArrowRight",
  Reply: "MessageCircle",
  Search: "MessageCircle",
  FileText: "Check",
  Building: "MessageCircle",
  PlusCircle: "CreditCard",
  Home: "MapPin",
  PhoneCall: "MessageCircle",
  Phone: "MessageCircle",
};

interface DuotoneIconProps {
  /** Base (subject) Lucide icon name, e.g. "DoorOpen". */
  name?: string;
  /** Red accent Lucide icon name. Falls back to a sensible default per base. */
  accent?: string;
  /** Path to a recoloured flat two-color SVG (e.g. "/icons2/vip.svg"). Preferred when set. */
  src?: string;
  /** Sizing only — pass Tailwind h-/w- (e.g. "h-7 w-7"). */
  className?: string;
  /** Set false to render the grey subject only (no red accent). */
  withAccent?: boolean;
}

/**
 * Concepts that have a brand-coloured Solar "Line Duotone" SVG in /public/icons2/.
 * Generated by scripts/gen-icons.mjs (grey line #52626F + red accent #D6071A).
 */
const GENERATED = new Set([
  "ClipboardList", "UserX", "UserCheck", "RefreshCw", "Lightbulb", "ListOrdered",
  "DoorOpen", "Target", "ShieldCheck", "CheckCircle", "Drama", "Heart", "BadgeCheck",
  "Megaphone", "Armchair", "Share2", "Flame", "BarChart2", "HelpCircle", "Ban",
  "Crown", "Shuffle", "Eye", "GitBranch", "Zap", "MessageCircle", "Users", "Phone",
  "Rocket", "Reply", "Search", "FileText", "Building", "PlusCircle", "ArrowRightLeft", "Home",
]);

export function DuotoneIcon({ name, accent, src, className, withAccent = true }: DuotoneIconProps) {
  const resolvedSrc = src ?? (name && GENERATED.has(name) ? `/icons2/${name}.svg` : undefined);
  // eslint-disable-next-line @next/next/no-img-element
  if (resolvedSrc) return <img src={resolvedSrc} alt="" aria-hidden className={cn("object-contain", className)} />;

  const Base = name ? REGISTRY[name] : undefined;
  if (!Base) return <span className={className} aria-hidden />;

  const accentName = accent ?? (name ? DEFAULT_ACCENT[name] : undefined);
  const Accent = withAccent && accentName ? REGISTRY[accentName] : undefined;

  return (
    <span className={cn("relative inline-block shrink-0", className)} aria-hidden>
      <Base
        className="absolute inset-0 h-full w-full"
        strokeWidth={ICON_STROKE}
        style={{ color: GREY }}
      />
      {Accent && (
        <span
          className="absolute grid place-items-center rounded-full bg-white"
          style={{ width: "60%", height: "60%", right: "-8%", bottom: "-8%" }}
        >
          <Accent
            className="h-[78%] w-[78%]"
            strokeWidth={ICON_ACCENT_STROKE}
            style={{ color: RED }}
          />
        </span>
      )}
    </span>
  );
}
